table 'Zones Dropoff'
	lineageTag: 3e6c2dfb-1d7e-4df2-8891-70acb04ed511

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 009ad99e-6438-4739-9c2f-965a45398388
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column borough
		dataType: string
		lineageTag: 2e49c754-bf7c-4c31-85a9-74700afd8ef0
		summarizeBy: none
		sourceColumn: borough

		annotation SummarizationSetBy = Automatic

	column zone
		dataType: string
		lineageTag: 9bc509e2-2dc6-4796-be1a-90dcde7fb603
		summarizeBy: none
		sourceColumn: zone

		annotation SummarizationSetBy = Automatic

	column service_zone
		dataType: string
		lineageTag: 77c45ae4-caec-47fd-9da1-fbfa4247342b
		summarizeBy: none
		sourceColumn: service_zone

		annotation SummarizationSetBy = Automatic

	column the_geom
		dataType: string
		lineageTag: c38a50c1-d506-4683-b5f9-56c8bd6130cf
		summarizeBy: none
		sourceColumn: the_geom

		annotation SummarizationSetBy = Automatic

	column shape_leng
		dataType: double
		lineageTag: ada8d92e-6c11-428a-9b83-eef97754f8e6
		summarizeBy: none
		sourceColumn: shape_leng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shape_area
		dataType: double
		lineageTag: 53b565bd-192e-47d1-bddc-b88121a5d8a9
		summarizeBy: none
		sourceColumn: shape_area

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column latitude
		dataType: double
		lineageTag: 9e291c55-a703-487b-9e91-227a80f6cdef
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 33cf0a83-50fb-4a46-9804-48ede625cefd
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Zones Dropoff' = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-c330c5c5-5531.cloud.databricks.com", "/sql/1.0/warehouses/623eacf84c6d44c1", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", Protocol=null]),
				    analytics_Database = Source{[Name="analytics",Kind="Database"]}[Data],
				    gold_Schema = analytics_Database{[Name="gold",Kind="Schema"]}[Data],
				    zones_View = gold_Schema{[Name="zones",Kind="View"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(zones_View, each ([the_geom] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

